filtersConfig:
  sharpen:
    id: sharpen
    label: SEN
    type: static
    disables:
      - contrast
    show: true
  highPenetrationFilter:
    id: highPenetrationFilter
    label: HI
    type: static
    disables:
      - contrast
    show: true
  invert:
    id: invert
    label: Invert
    type: static
    disables:
      - contrast
    show: true
  blackWhite:
    id: blackWhite
    label: BW
    type: static
    show: true
  varAbsorption:
    id: varAbsorption
    label: Vari
    type: volume
    initial:
      - 4
    bars: 9
    show: true
  contrast:
    id: contrast
    label: Contrast
    type: slider
    min: -4
    max: 4
    step: 0.01
    initial:
      - 0
    show: true
  osFilter:
    id: osFilter
    label: OS
    type: static
    disables:
      - o2Filter
    show: true
  o2Filter:
    id: o2Filter
    label: O2
    type: static
    disables:
      - osFilter
    show: true
